{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zbs.fullname" . }}
  labels:
    {{- include "zbs.labels" (dict "ctx" .) | nindent 4 }}
type: Opaque
stringData:
  ZBS_ZK_USERNAME: {{ .Values.secret.zkUsername | quote }}
  ZBS_ZK_PASSWORD: {{ .Values.secret.zkPassword | quote }}
  ZBS_S3_ACCESS_KEY_ID: {{ .Values.secret.s3AccessKeyId | quote }}
  ZBS_S3_SECRET_ACCESS_KEY: {{ .Values.secret.s3SecretAccessKey | quote }}
{{- end }}
